### PR TITLE
Winter 2016 Initial Schedule Commit

### PR DESCRIPTION
**Pull request by ElijahCaine**
Please suggest changes. @rettigs @lucywyman

### CODE REVIEW

**Comment by lucywyman** [comment]
+1 for now -- should we add activities in this PR, or in a separate one?

**Comment by ElijahCaine** [comment]
I'm adding the schedule in [the schedule etherpad](http://etherpad.osuosl.org/lugschedule2015). Commit pending.

**Comment by lucywyman** [comment]
:+1: :cake: :smiley:  :penguin:

**Comment by ElijahCaine** [comment]
Merging this in. We can make changes later.

**Pull request merged**
