### PR TITLE
turn the backups email into a blog post too

### PR DESCRIPTION
**Pull request by edunham**
please proof before merging.

### CODE REVIEW

**Comment by lucywyman** [comment]
@edunham lgtm -- thank you! :cat2:

**Comment by iankronquist** [comment]
I'm particularly interested in this because I don't have an effective backup solution right now. My home directory has more files than I can put on Flip (~20GB, if I recall) and I will quickly run out of space if I emailed them all to myself.

**Comment by ElijahCaine** [comment]
+1

**Comment by edunham** [comment]
@iankronquist not all the advice is relevant to everyone's situation... 

For your particular situation, have you considered getting a couple cheap external disks (http://www.newegg.com/Product/Product.aspx?Item=9SIA4UM1H81794 is one of myriad examples) and either cloning your repos of work onto them, rsyncing to them, or setting up RAID? If you're using cheap disks, you'll want some redundancy, because they can fail from time to time. 

Also when @lucywyman gets that server she won, she might let you back up stuff to it :floppy_disk:

**Comment by iankronquist** [comment]
@edunham That's a good idea, I'll look into that. I don't see it (or something similar) in the PR though. It might be worth mentioning.

**Comment by ElijahCaine** [comment]
@iankronquist This isn't particularly useful for a general advice blogpost but I use obnam with an 3TB external drive plugged into pi to do backups over my local network. If you've got more than 20GB you need to at some point purchase xGB of external space otherwise it's physically impossible to backup your files in any ultra secure manner.

**Pull request merged**
